modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "${issues_url}"
license = "${license}"

[[mods]]
modId = "${archives_name}"
version = "${version}"
displayName = "${display_name}"
authors = "${authors}"
description = '''${mod_description}'''
logoFile = "icon.png"

[[dependencies.beautify]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beautify]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beautify]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"
